apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: integration
      http:
        paths:
          - path: / # /banana
            pathType: Prefix
            backend:
              service:
                name: actuator-service # banana-service
                port:
                  number: 7003
